minVersion: 0.24.0
changelogPolicy: auto
preReleaseCommand: pwsh scripts/bump-version.ps1
targets:
  - name: github
    includeNames: /^sentry-unreal-.*.zip$/i
  - name: registry
    sdks:
      github:getsentry/sentry-unreal:
