on:
  workflow_call:
    inputs:
      unreal-version:
        required: true
        type: string
      backend:
        required: false
        type: string
        default: "crashpad"

jobs:
  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: recursive

      - name: Download sample build
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7
        with:
          name: UE ${{ inputs.unreal-version }} sample build (Linux, ${{ inputs.backend }})
          path: sample-build

      - name: Set execute permissions
        run: |
          chmod +x ${{ github.workspace }}/sample-build/SentryPlayground.sh
          chmod +x ${{ github.workspace }}/sample-build/SentryPlayground/Plugins/sentry/Binaries/Linux/*

      - name: Run integration tests
        id: run-integration-tests
        shell: pwsh
        working-directory: integration-test
        env:
          SENTRY_UNREAL_TEST_DSN: ${{ secrets.SENTRY_UNREAL_TEST_DSN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_API_TOKEN }}
          SENTRY_UNREAL_TEST_APP_PATH: ${{ github.workspace }}/sample-build/SentryPlayground.sh
        run: |
          cmake -B build -S .
          Invoke-Pester Integration.Desktop.Tests.ps1 -CI

      - name: Upload integration test output
        if: ${{ always() && steps.run-integration-tests.outcome == 'failure' }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: UE ${{ inputs.unreal-version }} integration test output (Linux, ${{ inputs.backend }})
          path: |
            integration-test/output/
            sample-build/SentryPlayground/Saved/Logs/
