on:
  workflow_call:
    inputs:
      runsOn:
        required: true
        type: string
      target:
        required: true
        type: string

jobs:
  download:
    runs-on: ${{ inputs.runsOn }}
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Select submodule
        id: env
        run: |
          if [[ "${{ inputs.target }}" == "Native" ]]; then
            submodule="modules/sentry-native"
          fi
          echo "submodule=$submodule" >> $GITHUB_OUTPUT

      - name: Get submodule status
        run: |          
          git submodule status --cached ${{ steps.env.outputs.submodule }} | tee submodule-status

      - name: Download
        run: |
          git submodule update --init --recursive ${{ steps.env.outputs.submodule }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.target }}-sdk
          path: ${{ steps.env.outputs.submodule }}
          retention-days: ${{ github.ref_name == 'main' && 14 || 1 }}
