name: submodule

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      path:
        required: true
        type: string

jobs:

  update:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Update submodule to the latest version
        id: target
        run: ./Scripts/update-submodule.ps1 -Path ${{ inputs.path }}

      - name: Get the base repo info
        if: steps.target.outputs.latestTag != steps.target.outputs.originalTag
        id: root
        run: |
          $mainBranch = $(git remote show origin | Select-String "HEAD branch: (.*)").Matches[0].Groups[1].Value
          Write-Host '::echo::on'
          Write-Host "::set-output name=baseBranch::$mainBranch"
          Write-Host "::set-output name=prBranch::deps/${{ inputs.path }}/${{ steps.target.outputs.latestTag }}"

      - name: Checkout submodule
        if: steps.target.outputs.latestTag != steps.target.outputs.originalTag
        run: ./Scripts/checkout-submodule.sh ${{ inputs.path }}

      - uses: vaind/download-artifact@989a39a417730897d098ab11c34e49ac4e13ed70
        if: ${{ inputs.name == 'Native SDK' && steps.target.outputs.latestTag != steps.target.outputs.originalTag }}
        with:
          name: Linux-SDK
          path: Source/ThirdParty/Linux
          wait-timeout: 3600

      - uses: vaind/download-artifact@989a39a417730897d098ab11c34e49ac4e13ed70
        if: ${{ inputs.name == 'Native SDK' && steps.target.outputs.latestTag != steps.target.outputs.originalTag }}
        with:
          name: Win64-SDK
          path: Source/ThirdParty/Win64
          wait-timeout: 3600

      - uses: vaind/download-artifact@989a39a417730897d098ab11c34e49ac4e13ed70
        if: ${{ inputs.name == 'Native SDK' && steps.target.outputs.latestTag != steps.target.outputs.originalTag }}
        with:
          name: Mac-SDK
          path: Source/ThirdParty/Mac
          wait-timeout: 3600

      - run: git --no-pager diff
        if: steps.target.outputs.latestTag != steps.target.outputs.originalTag

      - name: Create a PR
        if: steps.target.outputs.latestTag != steps.target.outputs.originalTag
        uses: peter-evans/create-pull-request@f22a7da129c901513876a2380e2dae9f8e145330
        with:
          base: ${{ steps.root.outputs.baseBranch }}
          branch: ${{ steps.root.outputs.prBranch }}
          commit-message: 'chore: update ${{ inputs.path }} to ${{ steps.target.outputs.latestTag }}'
          author: 'GitHub <noreply@github.com>'
          title: 'chore(deps): update ${{ inputs.name }} to ${{ steps.target.outputs.latestTagNice }}'
          body: |
            Bumps ${{ inputs.name }} from ${{ steps.target.outputs.originalTag }} to ${{ steps.target.outputs.latestTag }}.
            Auto-generated by a submodule dependency updater.
          labels: dependencies

      
