name: ue-docker

on: push

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.8'
          architecture: 'x64'

      - name: Install unreal-docker
        run: |
          pip install ue4-docker

      - name: Build Unreal Engine Docker image
        run: |
          ue4-docker setup
          ue4-docker build -basetag ltsc2019 --visual-studio 2019 --target minimal --exclude debug --exclude templates -isolation=process -username=${{ secrets.DOCKER_USERNAME }} -password=${{ secrets.DOCKER_TOKEN }} 4.27.0
