name: ue-docker

on: push

jobs:
  build:
    runs-on: windows-latest-4-cores
    steps:
      - name: Print disk space 1
        run: |
          Get-PSDrive

      - name: Clean up disk space
        run: |
          docker system prune -a -f
          Remove-Item -Path "C:\Android\android-sdk" -Force -Recurse

      - name: Print disk space 2
        run: |
          Get-PSDrive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.8'
          architecture: 'x64'

      - name: Install unreal-docker
        run: |
          pip install ue4-docker

      - name: Build Unreal Engine Docker image
        run: |
          ue4-docker setup
          ue4-docker build -basetag ltsc2022 --visual-studio 2022 --target minimal --exclude debug --exclude templates -isolation=process -username=${{ secrets.DOCKER_USERNAME }} -password=${{ secrets.DOCKER_TOKEN }} 5.3.2
