name: Build UE Windows Docker image

on:
  workflow_dispatch:
    inputs:
      ue_version:
        description: Select Unreal Engine version
        required: true
        type: choice
        options:
        - 4.27
        - 5.0
        - 5.1
        - 5.2
        - 5.3
        - 5.4
        - 5.5
      ue_repo:
        description: Set Unreal Engine repository
        required: true
        type: string
        default: 'https://github.com/getsentry/UnrealEngine.git'
      split_build:
        description: Split build into multiple jobs
        required: true
        type: boolean
        default: false

jobs:
  target-prerequisites:
    if: ${{ inputs.split_build == true }}
    uses: ./.github/workflows/docker-target-build.yml
    with:
      target: build-prerequisites
      runsOn: windows-latest-32-cores
      ue_version: ${{ inputs.ue_version }}
      ue_repo: ${{ inputs.ue_repo }}

  target-source:
    if: ${{ inputs.split_build == true }}
    needs: ${{ inputs.split_build == true && 'target-prerequisites' || '' }}
    uses: ./.github/workflows/docker-target-build.yml
    with:
      target: source
      runsOn: windows-latest-32-cores
      ue_version: ${{ inputs.ue_version }}
      ue_repo: ${{ inputs.ue_repo }}
    secrets: inherit

  target-minimal:
    needs: ${{ inputs.split_build == true && 'target-source' || '' }}
    uses: ./.github/workflows/docker-target-build.yml
    with:
      target: minimal
      runsOn: windows-latest-32-cores
      ue_version: ${{ inputs.ue_version }}
      ue_repo: ${{ inputs.ue_repo }}
    secrets: inherit
