name: UE Windows Docker build

on: push

jobs:
  build:
    # This will be replaced with `windows-latest-16-cores` once we get to building docker images
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean up disk space for Docker build
        shell: pwsh
        run: |
          ./${{ github.workspace }}/checkout/scripts/clean-storage-win.ps1

      # TODO Docker build steps